/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplicacao;

import banco.Banco;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.Livro;

/**
 *
 * @author rodri
 */
public class Biblioteca extends javax.swing.JFrame {
  
  private Banco banco;
  private ResultSet listaLivros;
  
  public void carregaListaLivros(){
    Livro livro = new Livro(banco.getConexao());
    try{
      listaLivros = livro.obterListaLivros();
    }
    catch(SQLException e){
      JOptionPane.showMessageDialog(this, "Erro ao obter a lista de livros.","Ocorreu um erro",JOptionPane.ERROR_MESSAGE);
    }
  }
  
  public void atualizaCampos(){
    try {
      lblIdLivro.setText(Integer.toString(listaLivros.getInt("idLivro")));
      txtTitulo.setText(listaLivros.getString("titulo"));
      txtAnoLancamento.setText(Integer.toString(listaLivros.getInt("anoLancamento")));
      txtNumeroPaginas.setText(Integer.toString(listaLivros.getInt("numeroPaginas")));
      cbIdioma.setSelectedItem(listaLivros.getString("idioma"));
      cbPaisOrigem.setSelectedItem(listaLivros.getString("paisOrigem"));
      txtResumo.setText(listaLivros.getString("resumo"));
    } 
    catch (SQLException ex) {
     JOptionPane.showMessageDialog(this, "Erro ao definir os valores nos campos.","Ocorreu um erro",JOptionPane.ERROR_MESSAGE);
    }
    
  }

  /**
   * Creates new form Biblioteca
   */
  public Biblioteca() {
    initComponents();
    //Caregando os ícones nos botões
    Icon iconePrimeiro = new ImageIcon("./icones/primeiro.png");
    Icon iconeAnterior = new ImageIcon("./icones/anterior.png");
    Icon iconeProximo = new ImageIcon("./icones/proximo.png");
    Icon iconeUltimo = new ImageIcon("./icones/ultimo.png");
    Icon iconeNovo = new ImageIcon("./icones/novo.png");
    Icon iconeSalvar = new ImageIcon("./icones/salvar.png");
    Icon iconeDeletar = new ImageIcon("./icones/deletar.png");
    btnPrimeiro.setIcon(iconePrimeiro);
    btnAnterior.setIcon(iconeAnterior);
    btnProximo.setIcon(iconeProximo);
    btnUltimo.setIcon(iconeUltimo);
    btnNovo.setIcon(iconeNovo);
    btnSalvar.setIcon(iconeSalvar);
    btnDeletar.setIcon(iconeDeletar);
    banco = new Banco("localhost", "3306", "root", "Nicolas13", "acervo");
    banco.realizaConexao();
    carregaListaLivros();
    if(!banco.getStatusConexao()){
      JOptionPane.showMessageDialog(this, "Erro ao conectar ao banco de dados.","Ocorreu um erro",JOptionPane.ERROR_MESSAGE);
    }
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method
   * is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPrimeiro = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();
        btnUltimo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblIdLivro = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtAnoLancamento = new javax.swing.JTextField();
        txtNumeroPaginas = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cbPaisOrigem = new javax.swing.JComboBox<>();
        cbIdioma = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtResumo = new javax.swing.JTextArea();
        btnNovo = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnDeletar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        btnPrimeiro.setMaximumSize(new java.awt.Dimension(50, 50));
        btnPrimeiro.setMinimumSize(new java.awt.Dimension(50, 50));
        btnPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrimeiroActionPerformed(evt);
            }
        });

        btnAnterior.setMaximumSize(new java.awt.Dimension(50, 50));
        btnAnterior.setMinimumSize(new java.awt.Dimension(50, 50));
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnProximo.setMaximumSize(new java.awt.Dimension(50, 50));
        btnProximo.setMinimumSize(new java.awt.Dimension(50, 50));
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        btnUltimo.setMaximumSize(new java.awt.Dimension(50, 50));
        btnUltimo.setMinimumSize(new java.awt.Dimension(50, 50));
        btnUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUltimoActionPerformed(evt);
            }
        });

        jLabel1.setText("Código livro:");

        jLabel3.setText("Título livro");

        jLabel4.setText("Ano de lançamento");

        jLabel5.setText("Número de páginas");

        jLabel6.setText("País de origem");

        cbPaisOrigem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Alemanha ", "Argentina", "Brasil", "Espanha", "EUA", "Inglaterra", "México", "Portugal" }));

        cbIdioma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione...", "Alemão", "Espanhol", "Inglês", "Português" }));

        jLabel7.setText("Idioma");

        jLabel8.setText("Resumo");

        txtResumo.setColumns(20);
        txtResumo.setRows(5);
        jScrollPane1.setViewportView(txtResumo);

        btnNovo.setMaximumSize(new java.awt.Dimension(50, 50));
        btnNovo.setMinimumSize(new java.awt.Dimension(50, 50));
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnSalvar.setMaximumSize(new java.awt.Dimension(50, 50));
        btnSalvar.setMinimumSize(new java.awt.Dimension(50, 50));
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnDeletar.setMaximumSize(new java.awt.Dimension(50, 50));
        btnDeletar.setMinimumSize(new java.awt.Dimension(50, 50));
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblIdLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(btnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(txtTitulo))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(txtAnoLancamento)
                                    .addComponent(jLabel6)
                                    .addComponent(cbPaisOrigem, 0, 124, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNumeroPaginas)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(cbIdioma, 0, 134, Short.MAX_VALUE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblIdLivro, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtAnoLancamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(txtNumeroPaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbPaisOrigem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    
  }//GEN-LAST:event_formWindowActivated

  private void btnPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrimeiroActionPerformed
    try{
      listaLivros.first();
      atualizaCampos();
    }
    catch(SQLException e){
      JOptionPane.showMessageDialog(this, "Não há registos.","Informação",JOptionPane.INFORMATION_MESSAGE);
    }
  }//GEN-LAST:event_btnPrimeiroActionPerformed

  private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
    try{
      if(listaLivros.previous())
        atualizaCampos();
      else
        JOptionPane.showMessageDialog(this, "Não há mais registros","Informação",JOptionPane.INFORMATION_MESSAGE);
    }
    catch(SQLException e){
      JOptionPane.showMessageDialog(this, "Não foi possível acessar os registros","Erro",JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_btnAnteriorActionPerformed

  private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
    try{
      if(listaLivros.next())
        atualizaCampos();
      else
        JOptionPane.showMessageDialog(this, "Não há mais registros","Informação",JOptionPane.INFORMATION_MESSAGE);
    }
    catch(SQLException e){
      JOptionPane.showMessageDialog(this, "Não foi possível acessar os registros","Erro",JOptionPane.ERROR_MESSAGE);
    }
  }//GEN-LAST:event_btnProximoActionPerformed

  private void btnUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUltimoActionPerformed
    try{
      listaLivros.last();
      atualizaCampos();
    }
    catch(SQLException e){
      JOptionPane.showMessageDialog(this, "Não há registos.","Informação",JOptionPane.INFORMATION_MESSAGE);
    }
  }//GEN-LAST:event_btnUltimoActionPerformed

  private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
    Livro livro = new Livro(banco.getConexao());
    livro.setAnoLancamento(Integer.parseInt(txtAnoLancamento.getText()));
    livro.setNumeroPaginas(Integer.parseInt(txtNumeroPaginas.getText()));
    livro.setIdioma((String) cbIdioma.getSelectedItem());
    livro.setPaisOrigem((String) cbPaisOrigem.getSelectedItem());
    livro.setTitulo(txtTitulo.getText());
    livro.setResumo(txtResumo.getText());
    try{
      if(lblIdLivro.getText().equals("")){
      //Novo livro
        livro.incluiLivro();
        lblIdLivro.setText(Integer.toString(livro.getIdLivro()));
        JOptionPane.showMessageDialog(this, "Registro salvo com sucesso!","Informação",JOptionPane.INFORMATION_MESSAGE);
      }
      else{
        //Atualiza livro
        livro.setIdLivro(Integer.parseInt(lblIdLivro.getText()));
        livro.atualizaLivro(Integer.parseInt(lblIdLivro.getText()));
        JOptionPane.showMessageDialog(this, "Registro alterado com sucesso!","Informação",JOptionPane.INFORMATION_MESSAGE);
      }
      carregaListaLivros();
    }
    catch(SQLException e){
      JOptionPane.showMessageDialog(this, "Ocorreu um erro ao salvar o livro","Erro",JOptionPane.ERROR_MESSAGE);
    }
      
   
  }//GEN-LAST:event_btnSalvarActionPerformed

  private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
      Livro livro = new Livro(banco.getConexao());
      try {
          if (lblIdLivro.getText().equals("")) {
              JOptionPane.showMessageDialog(this, "Não há nenhum registro selecionado.", "Erro", JOptionPane.ERROR_MESSAGE);
          } else {
              //Atualiza livro
              livro.setIdLivro(Integer.parseInt(lblIdLivro.getText()));
              livro.deletaLivro(Integer.parseInt(lblIdLivro.getText()));
              JOptionPane.showMessageDialog(this, "Registro deletado com sucesso!", "Informação", JOptionPane.INFORMATION_MESSAGE);
              lblIdLivro.setText("");
              txtTitulo.setText("");
              txtAnoLancamento.setText("");
              txtNumeroPaginas.setText("");
              txtResumo.setText("");
              cbIdioma.setSelectedIndex(0);
              cbPaisOrigem.setSelectedIndex(0);
          }
          carregaListaLivros();
      } catch (SQLException e) {
          JOptionPane.showMessageDialog(this, "Ocorreu um erro ao deletar o livro", "Erro", JOptionPane.ERROR_MESSAGE);
      }
  }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        lblIdLivro.setText("");
        txtTitulo.setText("");
        txtAnoLancamento.setText("");
        txtNumeroPaginas.setText("");
        txtResumo.setText("");
        cbIdioma.setSelectedIndex(0);
        cbPaisOrigem.setSelectedIndex(0);
    }//GEN-LAST:event_btnNovoActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Biblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Biblioteca().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnDeletar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnPrimeiro;
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnUltimo;
    private javax.swing.JComboBox<String> cbIdioma;
    private javax.swing.JComboBox<String> cbPaisOrigem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblIdLivro;
    private javax.swing.JTextField txtAnoLancamento;
    private javax.swing.JTextField txtNumeroPaginas;
    private javax.swing.JTextArea txtResumo;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
